- lib/main.dart
- lib/pages/home_page/borrowed_items_view.dart
- lib/pages/home_page/home_page.dart
- lib/pages/home_page/inventory_view.dart
- lib/services/firestore_service.dart
- lib/utilities/constants.dart
- lib/widgets/inventory_item_form.dart
- lib/widgets/inventory_list_item.dart
- test/test_helpers.dart
Extract Firestore queries into service methods.
This PR closes #20
> Add Firestore Service

- lib/business_logic/item_action.dart
- lib/dtos/user_dto.dart
- lib/entities/custom_user.dart
- lib/entities/inventory_item.dart
- lib/pages/home_page/inventory_view/inventory_view.dart
- lib/pages/home_page/settings_view/set_admins_button.dart
- lib/services/firestore_service.dart
- lib/widgets/inputs/multiselect_button.dart
- lib/widgets/inputs/multiselect_dialog.dart
- lib/widgets/inputs/value_selection_dialog.dart
- lib/widgets/inventory_list_item.dart
- test/widget_tests/borrowed_items_view_test.dart
- test/widget_tests/inventory_list_item_test.dart
- test/widget_tests/inventory_view_test.dart
- Add missing filter icon
- Add assign action
> Assignment Action

- lib/business_logic/item_action.dart
- lib/pages/home_page/inventory_view/filters/user_filter.dart
- lib/services/callable_service.dart
- lib/widgets/inputs/value_selection_dialog.dart
- test/widget_tests/inventory_view_test.dart
- Make assignment do unassignment
- Fix cancel button
- Cache user query
This PR closes #38
> Improve user assignment

- lib/widgets/inventory_list_item.dart
- pubspec.lock
- pubspec.yaml
Add animation to the item description page transition.
> Add animation

- analysis_options.yaml
- lib/business_logic/item_action.dart
- lib/entities/borrowing_rule.dart
- lib/pages/home_page/home_page.dart
- lib/pages/home_page/settings_view/borrowing_rules_setting/borrowing_rules_setting.dart
- lib/pages/home_page/settings_view/borrowing_rules_setting/decrease_button.dart
- lib/pages/home_page/settings_view/borrowing_rules_setting/delete_button.dart
- lib/pages/home_page/settings_view/borrowing_rules_setting/increase_button.dart
- lib/pages/home_page/settings_view/borrowing_rules_setting/item_type_edit_button.dart
- lib/pages/home_page/settings_view/borrowing_rules_setting/new_rule_button.dart
- lib/pages/home_page/settings_view/set_admins_button.dart
- lib/pages/home_page/settings_view/settings_view.dart
- lib/services/firestore_service.dart
- lib/widgets/buttons/async_elevated_button.dart
- lib/widgets/buttons/async_icon_button.dart
- lib/widgets/custom_layout_builder.dart
- lib/widgets/inputs/value_selection_dialog.dart
- test/helpers/test_helpers.dart
- test/integration_tests/integration_test.dart
- test/pages/home_page/borrowed_items_view_test.dart
- test/pages/home_page/inventory_view/inventory_view_test.dart
- test/pages/home_page/settings_view/settings_view_test.dart
- test/widgets/inventory_list_item_test.dart
> Add borrowing rules

- ios/Flutter/AppFrameworkInfo.plist
- ios/Podfile
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Info.plist
- lib/entities/inventory_item.dart
- lib/pages/home_page/borrowed_items_view.dart
- lib/pages/home_page/home_page.dart
- lib/pages/home_page/inventory_view/inventory_view.dart
- lib/pages/item_page.dart
- lib/pages/item_page/item_history.dart
- lib/pages/item_page/item_page.dart
- lib/services/firestore_service.dart
- lib/widgets/inventory_list_item.dart
- lib/widgets/item_actions_button.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- test/pages/home_page/inventory_view/inventory_view_test.dart
- test/pages/home_page/item_page_test.dart
- test/widgets/inventory_list_item_test.dart
- Add qr code scanning
- Scan item qr code and navigate to page
- Add actions to item page
- Extract options into separate widget
- Display errors if scan failed
This PR closes #56
> Support QR code scanning

- lib/business_logic/borrowing_request_dialog.dart
- lib/business_logic/item_action.dart
- lib/main.dart
- lib/pages/home_page/borrowed_items_view.dart
- lib/pages/home_page/borrowing_requests_view/borrowing_request_action_button.dart
- lib/pages/home_page/borrowing_requests_view/filtered_borrowing_requests_section.dart
- lib/pages/home_page/home_page.dart
- lib/pages/home_page/inventory_view/inventory_view.dart
- lib/pages/home_page/settings_view/borrowing_rules_setting/borrowing_rules_setting.dart
- lib/pages/home_page/settings_view/borrowing_rules_setting/decrease_button.dart
- lib/pages/home_page/settings_view/borrowing_rules_setting/delete_button.dart
- lib/pages/home_page/settings_view/borrowing_rules_setting/increase_button.dart
- lib/pages/home_page/settings_view/borrowing_rules_setting/item_type_edit_button.dart
- lib/pages/home_page/settings_view/borrowing_rules_setting/new_rule_button.dart
- lib/pages/item_page/item_page.dart
- lib/repository_registrant.dart
- lib/services/firestore_service.dart
- lib/services/repositories/borrowing_request_repository.dart
- lib/services/repositories/borrowing_rule_repository.dart
- lib/services/repositories/inventory_item_repository.dart
- lib/services/repositories/repositories.dart
- lib/widgets/inventory_list_item/inventory_item_form.dart
- lib/widgets/print_dialog/print_dialog_body.dart
- test/helpers/test_helpers.dart
- test/pages/home_page/borrowed_items_view_test.dart
- Extract inventory item repository
- Extract Borrowing Rule repository
- Extract Borrowing Request Repository
- Extract repository registrant
> Firestore Service refactor

- build.yaml
- lib/pages/home_page/borrowed_items_view.dart
- lib/pages/home_page/inventory_view/inventory_view.dart
- lib/widgets/inventory_list_item_loading.dart
- lib/widgets/loading_placeholder.dart
- pubspec.lock
- pubspec.yaml
Adds an inamted loading state for the items list
> Loading State

- lib/pages/home_page/settings_view/borrowing_rules_setting/borrowing_rules_setting.dart
- lib/pages/home_page/settings_view/settings_view.dart
- lib/pages/home_page/settings_view/users_setting/users_setting.dart
Improve settings layout
This PR closes #67
> User Assignment cleanup

- lib/business_logic/item_action.dart
- lib/pages/item_page/item_history.dart
- lib/repository_registrant.dart
- lib/services/firestore_service.dart
- lib/services/repositories/event_repository.dart
- lib/services/repositories/inventory_item_repository.dart
- lib/services/repositories/repositories.dart
- lib/widgets/inventory_list_item/inventory_item_form.dart
- test/business_logic/borrowing_request_dialog_test.dart
- test/helpers/test_helpers.dart
- test/integration_tests/integration_test.dart
- test/pages/home_page/borrowed_items_view_test.dart
- test/pages/home_page/borrowing_requests_view/borrowing_requests_list_item_test.dart
- test/pages/home_page/borrowing_requests_view/borrowing_requests_view_test.dart
- test/pages/home_page/borrowing_requests_view/filtered_borrowing_requests_section_test.dart
- test/pages/home_page/inventory_view/inventory_view_test.dart
- test/pages/home_page/settings_view/settings_view_test.dart
- test/pages/item_page_test.dart
- test/widgets/inventory_item_form_test.dart
- test/widgets/inventory_list_item_test.dart
- Add "Create" event
- Add "Update" event
- Introduce `EventRepository`
- Refactor auth mocks in tests
This PR closes #48
> Add Create/Update events

- lib/repository_registrant.dart
- lib/utilities/theme.dart
- lib/widgets/inputs/borrower_input.dart
- lib/widgets/inventory_list_item/inventory_item_form.dart
- lib/widgets/inventory_list_item/laptop_form_fields.dart
- test/helpers/test_helpers.dart
- test/integration_tests/integration_test.dart
- test/pages/home_page/inventory_view/inventory_view_test.dart
- test/widgets/inventory_item_form_test.dart
- adds ability to unset storage location
- improves input styling
- adds "*" to required inputs
- adds a borrower input to the form
This PR closes #71
> Item Form Improvements

- lib/entities/inventory_item.dart
- lib/pages/home_page/borrowed_items_view.dart
- lib/pages/home_page/inventory_view/inventory_view.dart
- lib/widgets/inventory_list_item/inventory_item_form.dart
- sort items in inventory view
- sort items in borrowed items view
This PR closes #70
> Implement Sorting

- lib/business_logic/item_action.dart
- lib/widgets/inventory_list_item/item_actions_button.dart
- test/pages/home_page/borrowed_items_view_test.dart
- test/widgets/item_actions_button_test.dart
Admins will now always see the "Release" action for a borrowed item
This PR closes #72
> Enable Release action for Admins

- lib/business_logic/item_action.dart
- lib/entities/inventory_item.dart
- lib/services/print_service.dart
- lib/widgets/dialogs/print_dialog/print_dialog_mobile.dart
- lib/widgets/dialogs/print_dialog/print_dialog_web.dart
- lib/widgets/inventory_list_item/inventory_item_form.dart
- pubspec.lock
- test/entities/inventory_item_test.dart
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
- Update dependencies
- Swap field order
- Add item name to label
- Move trademark to the top of label
> General improvements

- lib/business_logic/item_action.dart
- lib/main.dart
- lib/pages/home_page/inventory_view/filters/search_field.dart
- lib/pages/home_page/inventory_view/inventory_view.dart
- lib/pages/home_page/inventory_view/inventory_view_list.dart
- lib/pages/home_page/inventory_view/selection_actions.dart
- lib/widgets/dialogs/print_dialog/print_dialog_mobile.dart
- lib/widgets/dialogs/print_dialog/print_dialog_web.dart
- lib/widgets/error_container.dart
- lib/widgets/inventory_list_item.dart
- pubspec.lock
- test/pages/home_page/inventory_view/inventory_view_list_test.dart
- test/pages/home_page/inventory_view/inventory_view_test.dart
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
- Make inventory list items selectable
- Make items selected on single click in selection mode Co-authored-by: Alisa Vynohradova <56138100+alisondraV@users.noreply.github.com>
- Add selection actions in selection mode
- Implement deselect all
- Implement select all
- Support printing multiple items
> Bulk item printing

- lib/pages/home_page/home_page.dart
- test/pages/home_page/inventory_view/inventory_view_test.dart
Disables the "Add" button for regular users
This PR closes #87
> Disable adding items for regular users

- devtools_options.yaml
- lib/pages/home_page/inventory_view/inventory_view_list.dart
Make inventory list scrollable
This PR closes #89
> Make inventory list scrollable again

- lib/pages/home_page/home_page.dart
- lib/pages/home_page/tab_factory.dart
- test/pages/home_page/home_page_test.dart
- Rename borrowed items
- Switch order of first 2 tabs depending on the role
- Create TabFactory
- Add page titles list to the factory
- Extract desktop pages
- Refactor repetition
> Conditional tab order

- lib/pages/home_page/home_page.dart
- lib/pages/home_page/settings_view/settings_view.dart
- lib/widgets/buttons/logout_button.dart
- test/pages/home_page/settings_view/settings_view_test.dart
Move logout button to settings
This PR closes #90
> Move Logout button

- lib/pages/home_page/borrowing_requests_view/borrowing_request_action_button.dart
- test/pages/home_page/borrowing_requests_view/borrowing_requests_list_item_test.dart
Does not assign the borrower when denying a borrowing request.
This PR closes #92
> Fix denying borrowing requests

- lib/pages/home_page/settings_view/borrowing_rules_setting/borrowing_rules_setting.dart
Allows defining a borrowing rule with count of `0`
This PR closes #95
> Make Borrowing Rules stricter

- .github/workflows/test-and-build.yml
- android/app/build.gradle
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/settings.gradle
- lib/pages/home_page/borrowing_requests_view/filtered_borrowing_requests_section.dart
- lib/pages/item_page/item_history.dart
- lib/widgets/empty_list_state.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- test/helpers/test_helpers.dart
- test/pages/home_page/borrowing_requests_view/filtered_borrowing_requests_section_test.dart
- test/pages/item_page_test.dart
Co-authored-by: Alisa Vynohradova <56138100+alisondraV@users.noreply.github.com>
> Change borrowing requests language
